### ISSUE TITLE
Fails to build on Windows

### ISSUE THREAD

**Issue by ahodges9** [katyo/aubio-rs#1]
I am not able to get this crate to build on Windows. Any plans to add support?

**Comment by ahodges9** [comment]
Looks to be failing due to WAF (whats used to compile the C library) not being able to find stdlid.h...

Did some digging and this looks to be due to how WAF generates the path. It uses relative paths which quickly exceeds the max path limits of MSVC given the deep nature of the Rust build folders. So I can easily compile aubio when cloning into c:\aubio, but when its c:\aubio-rs\target\debug\build\aubio-lib-ca65db37df494adb\out\build\0.4.9\ MSVC gets very unhappy.

This looks to be fixed in some dev branches of WAF: https://gitlab.com/ita1024/waf/-/commit/13d9c8566cb938cec12fab3cf731409366dbf8f7

**Comment by katyo** [comment]
I temporarily refused windows support due to some issues which is hard to resolve for me because I haven't experience in windows.
Some time ago I already tried to get it works using mingw32 toolchain on travis-ci but I failed.
You feel free to help me with it, PRs are welcome.

**Comment by katyo** [comment]
@ahodges9 Can you test this branch https://github.com/katyo/aubio-rs/tree/waf-update?

**Comment by scratchyone** [comment]
@katyo not sure if you've tested it already, but I just tried that version and it doesn't work

**Comment by katyo** [comment]
Possibly fixed by #9.

To @ahodges9, @scratchyone.
Can you help to test master branch again?

**Comment by katyo** [comment]
I hope this issue is solved for now.
Feel free to re-open it.
