### ISSUE TITLE
How do I import the aubio-rs crate in the main file and how do I get started with it? 

### ISSUE THREAD

**Issue by Joe23232** [katyo/aubio-rs#12]
So with this crate: https://docs.rs/aubio-rs/0.1.3/aubio_rs/

I already put it in the `Cargo.toml` file, but in the `main.rs` file how would I import this library?

I additionally want to know how do I get started with this as I am very lost. How would I import a music and start analysing the data on the song etc?

Another question is am I able to determine beats per second, the loudness in the current point of the music, the pitch/key signature and play the audio file or do I need another library/crate?

**Comment by katyo** [comment]
Fisrt, you can load wave (sound) data using another crates (ex. hound for .wav).
To determine beats rate use [Tempo](https://docs.rs/aubio-rs/0.1.3/aubio_rs/struct.Tempo.html) detection.

See example [notes.rs](https://github.com/katyo/aubio-rs/blob/master/aubio-rs/examples/notes.rs) which demonstrates how to determine notes in music.
See also [aubio docs](https://aubio.org/doc/latest/).

**Comment by Joe23232** [comment]
> Fisrt, you can load wave (sound) data using another crates (ex. hound for .wav).

Does this crate support `mp3` formats as well?

**Comment by katyo** [comment]
> > Fisrt, you can load wave (sound) data using another crates (ex. hound for .wav).
> 
> Does this crate support `mp3` formats as well?

I don't know, I assume that only .wav is supported. But there is several crates to decode mp3.
